# Generated by Django 5.0.2 on 2024-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BestSeller",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="bestseller_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="collection_images/")),
                ("reviews_count", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(default="Default description", max_length=500),
                ),
                ("sizes", models.JSONField(blank=True, default=list, null=True)),
                (
                    "description2",
                    models.CharField(default="Default description", max_length=500),
                ),
                (
                    "related_images",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="shop_images/")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("Men", "Men"), ("Women", "Women"), ("Kids", "Kids")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Topwear", "Topwear"),
                            ("Bottomwear", "Bottomwear"),
                            ("Winterwear", "Winterwear"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
