# Generated by Django 5.0.2 on 2024-10-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="reviews_count",
            field=models.IntegerField(),
        ),
    ]
