# Generated by Django 5.0.2 on 2024-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_collection_reviews_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="collection",
            name="related_images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="sizes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
