# Generated by Django 5.0.2 on 2024-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_collection_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="related_images",
            field=models.ImageField(upload_to="collection_images/"),
        ),
    ]
